# Generated by Django 5.2.3 on 2025-07-01 14:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="admin",
                max_length=150,
                unique=True,
                verbose_name="Имя пользователя",
            ),
            preserve_default=False,
        ),
    ]
