# Generated by Django 5.2.3 on 2025-06-29 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=89028182967,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допускается только российский номер телефона",
                        regex="^8\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
            preserve_default=False,
        ),
    ]
