# Generated by Django 5.2.3 on 2025-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="troshakotik@gmail.com",
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
            preserve_default=False,
        ),
    ]
