# Generated by Django 5.2.3 on 2025-07-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_cover_alter_review_author_alter_review_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [("special_status", "Can read all books")],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
