# Generated by Django 5.2.3 on 2025-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
