# Generated by Django 5.2.3 on 2025-07-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_id_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="id_index",
        ),
    ]
